[CGE][#1] Page 1 with Searchbar
ProjetSI-FC/front pull request #10
Opened 2023-11-28 08:36 UTC by CorentinAuTibet

The first page with the autocomplete search bar and 2 buttons. 1 deleting button and a search button to go on page 2

2023-11-28 16:38 UTC, TheDestiny45 requested changes
Small changes need to be taken into account

2023-11-28 16:38 UTC, TheDestiny45 commented on src/app/pages/secondary-page/secondary-page.component.html
Rename 'secondary-page' to 'result-page' ?

2023-11-28 16:38 UTC, TheDestiny45 commented on src/app/shared-component/keyword.ts
To delete

2023-11-28 16:38 UTC, TheDestiny45 commented on src/styles.scss
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
```suggestion
html, body { height: 100%; }
body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
```

2023-12-04 10:07 UTC, TheoSouchon commented on src/app/pages/home-page/home-page.component.ts
import unused

2023-12-04 10:26 UTC, TheDestiny45 approved these changes

2023-12-12 07:21 UTC, baptiste1403 approved these changes

2024-01-08 13:34 UTC, merged